#!/usr/bin/with-contenv bash

echo "*** Ansible Installer ***"
echo "Checking if ansible is installed"

if ! command -v ansible &> /dev/null; then
    echo "ansible is not installed, adding to installation queue"
    echo "ansible" >> /mod-pip-packages-to-install.list
    if ! command -v pip3 &> /dev/null; then
        echo "pip3 is not installed, adding to installation queue"
        echo "python3 python3-pip" >> /mod-repo-packages-to-install.list
    fi
    pip3 install ansible
else
    echo "ansible is already installed, skipping!"
fi

echo "*** Ansible-lint installer"
echo "Checking if ansible-lint is installed"

if ! command -v ansible-lint &> /dev/null; then
        echo "ansible-lint is not installed, adding to installation queue"
        echo "ansible" >> /mod-pip-packages-to-install.list
else
        echo "ansible-lint is already installed"
fi
